swagger: "2.0"
info:
  description: "音楽PlatformのAPI仕様。\n
    楽曲関連のAPIを本ドキュメント内で定義する。"
  version: "1.0.0"
  title: "Music-PF API (music)"
  license:
    name: "Apache 2.0"
    url: "http://www.apache.org/licenses/LICENSE-2.0.html"
host: "petstore.swagger.io"
basePath: "/v1"
tags:
- name: "music"
  description: "楽曲情報についてのAPI"
- name: "instrumentation"
  description: "楽器編成に関するAPI"
schemes:
- "https"
- "http"
paths:
  /music:
    post:
      tags:
      - "music"
      summary: "楽曲情報を登録する"
      responses:
        "400":
          description: "不正な入力"
  /music/search:
    post:
      tags:
      - "music"
      summary: "楽曲を検索する"
      responses:
        "400":
          description: "不正な入力"

  /music/instrumentation:
    post:
      tags:
      - "instrumentation"
      summary: "楽器編成を新規登録する"
      responses:
        "400":
          description: "不正な入力"
  /music/instrumentation/search:
    post:
      tags:
      - "instrumentation"
      summary: "楽器編成を検索する"
      responses:
        "400":
          description: "不正な入力"
  /music/instrumentation/{id}:
    get:
      tags:
      - "instrumentation"
      summary: "{id}の楽器編成の詳細を取得する"
      description: ""
      operationId: "getInstrumentation"
      produces:
      - "application/json"
      parameters:
      - name: "id"
        in: "path"
        description: "楽器編成ID"
        required: true
        type: "string"
        format: "string"
      responses:
        "400":
          description: "不正な入力"
    put:
      tags:
      - "instrumentation"
      summary: "{id}の楽器編成の詳細を更新する"
      description: ""
      operationId: "updateInstrumentation"
      produces:
      - "application/json"
      parameters:
      - name: "id"
        in: "path"
        description: "楽器編成ID"
        required: true
        type: "string"
        format: "string"
      responses:
        "400":
          description: "不正な入力"
    delete:
      tags:
      - "instrumentation"
      summary: "{id}の楽器編成を削除する"
      description: ""
      operationId: "deleteInstrumentation"
      produces:
      - "application/json"
      parameters:
      - name: "id"
        in: "path"
        description: "楽器編成ID"
        required: true
        type: "string"
        format: "string"
      responses:
        "400":
          description: "不正な入力"

  /music/instrumentation/instrument:
    post:
      tags:
      - "instrumentation"
      summary: "新しい楽器を登録する"
      description: "楽器編成に使われる楽器を新規登録する。"
      operationId: "newInstrument"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      - in: "body"
        name: "body"
        description: "登録する楽器情報のオブジェクト"
        required: true
        schema:
          $ref: "#/definitions/instrument"
      responses:
        "400":
          description: "不正な入力"
definitions:
  instrument:
    type: "object"
    description: "楽器の情報"
    required:
    - "ja_jp"
    - "en_us"
    - "abbreviation"
    - "category_id"
    properties:
      id:
        type: "string"
        format: "string"
        description: "ID。指定ない場合はen_usの値となる。"
      ja_jp:
        type: "string"
        format: "string"
        description: "楽器の日本語名"
      en_us:
        type: "string"
        format: "string"
        description: "楽器の英語名"
      it_it:
        type: "string"
        format: "string"
        description: "楽器のイタリア語名。指定ない場合は空となる。"
      abbreviation:
        type: "string"
        format: "string"
        description: "楽器の短縮名"
      category_id:
        type: "string"
        description: "楽器の分類"
        enum:
        - "woodwind"
        - "brass"
        - "percussion"
        - "string"
        - "keyboard"
        - "voice"
        - "other"
      is_usual:
        type: "boolean"
        default: true
        description: "通常使われる楽器かどうか。falseは特殊楽器を指す。"
#  instrument_category:
#    type: "object"
#    description: "楽器の分類"
#    required:
#    - "id"
#    - "ja_jp"
#    - "en_us"
#    properties:
#      id:
#        type: "string"
#        format: "string"
#        description: "ID"
#      ja_jp:
#        type: "string"
#        format: "string"
#        description: "楽器分類の日本語名"
#      en_us:
#        type: "string"
#        format: "string"
#        description: "楽器分類の日本語名"
