swagger: "2.0"
info:
  description: |
    音楽PlatformのAPI仕様。
    楽曲関連のAPIを本ドキュメント内で定義する。
  version: "1.0.0"
  title: "Music-PF API (music)"
  license:
    name: "Apache 2.0"
    url: "http://www.apache.org/licenses/LICENSE-2.0.html"
host: "<url-id>.lambda-url.<region>.on.aws"
basePath: "/v1"
tags:
- name: "dev"
  description: "開発用API"
- name: "music"
  description: "楽曲情報についてのAPI"
- name: "instrumentation"
  description: "楽器編成に関するAPI"
- name: "instrument"
  description: "楽器に関するAPI"
schemes:
- "https"
paths:
  # /dev/tables/summary:
  #   get:
  #     tags:
  #     - "dev"
  #     summary: "【開発用】主要なデータをすべて取得する"
  #     description: |
  #       主要なデータをすべて取得する。
  #       データ閲覧用。
  #       将来このAPIは隠蔽する。
  #     parameters:
  #     - name: "target"
  #       in: "query"
  #       description: "取得対象のデータ分類"
  #       required: true
  #       type: "string"
  #       enum:
  #       - "music"
  #     responses:
  #       "200":
  #         description: "成功"
  #         schema:
  #           $ref: "#/definitions/musicSummary"
  #       "400":
  #         description: "不正な入力"
  #         schema:
  #           $ref: "#/definitions/errorResponse"
  # /music:
  #   post:
  #     tags:
  #     - "music"
  #     summary: "【未定義】楽曲情報を登録する"
  #     responses:
  #       "400":
  #         description: "不正な入力"
  # /music/search:
  #   post:
  #     tags:
  #     - "music"
  #     summary: "【未定義】楽曲を検索する"
  #     responses:
  #       "400":
  #         description: "不正な入力"

  # /music/instrumentation:
  #   post:
  #     tags:
  #     - "instrumentation"
  #     summary: "【未定義】楽器編成を新規登録する"
  #     responses:
  #       "400":
  #         description: "不正な入力"
  # /music/instrumentation/search:
  #   post:
  #     tags:
  #     - "instrumentation"
  #     summary: "【未定義】楽器編成を検索する"
  #     responses:
  #       "400":
  #         description: "不正な入力"
  # /music/instrumentation/{id}:
  #   get:
  #     tags:
  #     - "instrumentation"
  #     summary: "【未定義】{id}の楽器編成の詳細を取得する"
  #     description: ""
  #     operationId: "getInstrumentation"
  #     produces:
  #     - "application/json"
  #     parameters:
  #     - name: "id"
  #       in: "path"
  #       description: "楽器編成ID"
  #       required: true
  #       type: "string"
  #       format: "string"
  #     responses:
  #       "400":
  #         description: "不正な入力"
  #   put:
  #     tags:
  #     - "instrumentation"
  #     summary: "【未定義】{id}の楽器編成の詳細を更新する"
  #     description: ""
  #     operationId: "updateInstrumentation"
  #     produces:
  #     - "application/json"
  #     parameters:
  #     - name: "id"
  #       in: "path"
  #       description: "楽器編成ID"
  #       required: true
  #       type: "string"
  #       format: "string"
  #     responses:
  #       "400":
  #         description: "不正な入力"

  /music/instrumentation/instrument:
    post:
      tags:
      - "instrument"
      summary: "新しい楽器を登録する"
      description: "楽器編成に使われる楽器を新規登録する。"
      operationId: "postInstrument"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      - in: "body"
        name: "body"
        description: "登録する楽器情報のオブジェクト"
        required: true
        schema:
          type: "object"
          properties:
            instrument:
              $ref: "#/definitions/instrumentPost"
      responses:
        "200":
          description: "成功"
        "400":
          description: "不正な入力"
          schema:
            $ref: "#/definitions/errorResponse"
    delete:
      tags:
      - "instrument"
      summary: "使われていない楽器を削除する"
      description: "編成情報に紐づいていない楽器をすべて削除する"
      operationId: "deleteInstruments"
      produces:
      - "application/json"
      responses:
        "200":
          description: "削除した楽器の一覧"
          schema:
            type: "object"
            properties:
              deletedInstruments:
                type: "array"
                description: "楽器情報の一覧"
                items:
                  $ref: "#/definitions/instrument"
  /music/instrumentation/instrument/{id}:
    get:
      tags:
      - "instrument"
      summary: "楽器の詳細を取得する"
      description: "楽器の詳細を取得する"
      operationId: "getInstrument"
      produces:
      - "application/json"
      parameters:
      - name: "id"
        in: "path"
        description: "楽器ID"
        required: true
        type: "string"
      responses:
        "200":
          description: "成功"
        "400":
          description: "不正な入力"
          schema:
            $ref: "#/definitions/errorResponse"
    put:
      tags:
      - "instrument"
      summary: "楽器情報を更新する"
      description:
        "楽器情報を更新する。"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      - name: "id"
        in: "path"
        description: "楽器ID"
        required: true
        type: "string"
      - name: "body"
        in: "body"
        description: "更新内容"
        required: true
        schema:
          type: "object"
          properties:
            instrument:
              $ref: "#/definitions/instrumentUpdate"
      responses:
        "200":
          description: "成功"
        "400":
          description: |
            不正な入力
            * パスのidが存在しない
            * ボディのidがすでに存在する
            * ボディのcategoryIdが存在しない
          schema:
            $ref: "#/definitions/errorResponse"

definitions:
  # musicSummary:
  #   type: "object"
  #   description: "すべてのテーブル情報"
  #   properties:
  #     musics:
  #       type: "array"
  #       items:
  #         $ref: "#/definitions/music"
  #     musicCategories:
  #       type: "array"
  #       items:
  #         $ref: "#/definitions/musicCategory"
  #     creators:
  #       type: "array"
  #       items:
  #         $ref: "#/definitions/creator"
  #     countries:
  #       type: "array"
  #       items:
  #         $ref: "#/definitions/country"
  #     instrumentations:
  #       type: "array"
  #       items:
  #         $ref: "#/definitions/instrumentation"
  #     instrumentationCategories:
  #       type: "array"
  #       items:
  #         $ref: "#/definitions/instrumentationCategory"
  #     instruments:
  #       type: "array"
  #       items:
  #         $ref: "#/definitions/instrument"
  #     instrumentCategories:
  #       type: "array"
  #       items:
  #         $ref: "#/definitions/instrumentCategory"

  # music:
  #   type: "object"
  #   description: "楽曲情報"
  # musicCategory:
  #   type: "object"
  #   description: "楽曲の分類"
  # creator:
  #   type: "object"
  #   description: "作曲者・編成者情報"
  # country:
  #   type: "object"
  #   description: "国情報"
  # instrumentation:
  #   type: "object"
  #   description: "編成情報"
  # instrumentationCategory:
  #   type: "object"
  #   description: "編成の分類"
  instrument:
    type: "object"
    description: "楽器の情報"
    properties:
      id:
        type: "string"
        format: "string"
        description: "ID。指定ない場合はenUsの値となる。"
        example: "flute"
      jaJp:
        type: "string"
        format: "string"
        description: "楽器の日本語名"
        example: "フルート"
      enUs:
        type: "string"
        format: "string"
        description: "楽器の英語名"
        example: "flute"
      itIt:
        type: "string"
        format: "string"
        description: "楽器のイタリア語名。指定ない場合は空となる。"
        example: "flauto"
      abbreviation:
        type: "string"
        format: "string"
        description: "楽器の短縮名"
        example: "Fl."
      categoryId:
        type: "string"
        description: "楽器の分類"
        enum:
        - "woodwind"
        - "brass"
        - "percussion"
        - "string"
        - "keyboard"
        - "voice"
        - "other"
        example: "woodwind"
      isUsual:
        type: "boolean"
        default: true
        description: "よく使われる楽器かどうか。falseは特殊楽器を指す。"
        example: true
  instrumentPost:
    type: "object"
    description: "楽器の登録情報"
    required:
    - "jaJp"
    - "enUs"
    - "abbreviation"
    - "categoryId"
    properties:
      id:
        type: "string"
        format: "string"
        description: "ID。指定ない場合はenUsの値となる。"
        example: "flute"
      jaJp:
        type: "string"
        format: "string"
        description: "楽器の日本語名"
        example: "フルート"
      enUs:
        type: "string"
        format: "string"
        description: "楽器の英語名"
        example: "flute"
      itIt:
        type: "string"
        format: "string"
        description: "楽器のイタリア語名。指定ない場合は空となる。"
        example: "flauto"
      abbreviation:
        type: "string"
        format: "string"
        description: "楽器の短縮名"
        example: "Fl."
      categoryId:
        type: "string"
        description: "楽器の分類"
        enum:
        - "woodwind"
        - "brass"
        - "percussion"
        - "string"
        - "keyboard"
        - "voice"
        - "other"
        example: "woodwind"
      isUsual:
        type: "boolean"
        default: true
        description: "よく使われる楽器かどうか。falseは特殊楽器を指す。"
        example: true
  instrumentUpdate:
    type: "object"
    description: "楽器の更新内容"
    properties:
      id:
        type: "string"
        format: "string"
        description: "ID"
        example: "flute"
      jaJp:
        type: "string"
        format: "string"
        description: "楽器の日本語名"
        example: "フルート"
      enUs:
        type: "string"
        format: "string"
        description: "楽器の英語名"
        example: "flute"
      itIt:
        type: "string"
        format: "string"
        description: "楽器のイタリア語名"
        example: "flauto"
      abbreviation:
        type: "string"
        format: "string"
        description: "楽器の短縮名"
        example: "Fl."
      categoryId:
        type: "string"
        description: "楽器の分類"
        enum:
        - "woodwind"
        - "brass"
        - "percussion"
        - "string"
        - "keyboard"
        - "voice"
        - "other"
        example: "woodwind"
      isUsual:
        type: "boolean"
        default: true
        description: "よく使われる楽器かどうか。falseは特殊楽器を指す。"
        example: true
  # instrumentCategory:
  #   type: "object"
  #   description: "楽器の分類"
  #   required:
  #   - "id"
  #   - "jaJp"
  #   - "enUs"
  #   properties:
  #     id:
  #       type: "string"
  #       format: "string"
  #       description: "ID"
  #       example: "woodwind"
  #     jaJp:
  #       type: "string"
  #       format: "string"
  #       description: "楽器分類の日本語名"
  #       example: "木管楽器"
  #     enUs:
  #       type: "string"
  #       format: "string"
  #       description: "楽器分類の日本語名"
  #       example: "woodwind"

  errorResponse:
    type: "object"
    description: "エラーレスポンス"
    required:
    - "error"
    properties:
      error:
        type: "object"
        description: "エラー情報"
        required:
        - "id"
        - "message"
        properties:
          id:
            type: "string"
            format: "string"
            description: "エラーID"
            example: "errorId"
          message:
            type: "string"
            format: "string"
            description: "エラーメッセージ"
            example: "error message"